### ISSUE TITLE
Netlify Support?

### ISSUE THREAD

**Issue by Deco354** [mannberg/splashtag#3]
Hey first of all thanks for making this it's very useful and I've enjoyed using it.

Can this plugin work with hosting platforms like netlify? Everything runs perfectly locally but not on netlify. I suspect it's because netlify's build server doesn't have Splash installed so I'm likely asking the impossible but thought I'd check all the same if there's a way to enable this plugin to work on a build server.

**Comment by mannberg** [comment]
Cool to hear you’re enjoying this! Like you say, Netlify’s server or any other machine would need to have Splash installed to make use of this. My best bet would be to contact them :)

Cheers!

**Comment by hybridcattt** [comment]
I've managed to make it work with Netlify. It's been a year since the original post so not sure if it's still relevant for you @Deco354 . Posting here for anyone who might need this. 

Instead of using `jekyll build` as a build command, I made an sh script with following content: 

```bash
git clone https://github.com/johnsundell/splash.git
cd splash

swift build -c release
install .build/release/SplashHTMLGen ../SplashHTMLGen

cd ..
JEKYLL_ENVIRONMENT=production jekyll build # just your normal build command here
```

Then I altered my copy of the plugin on line 12, so it expects a local executable of Splash instead of expecting it to be installed system-wide:

```ruby
command = Shellwords.join(['./SplashHTMLGen', input])
# before:  
# command = Shellwords.join(['SplashHTMLGen', input])
````

Also notice I'm using lowercase `release` in `.build/release/SplashHTMLGen`, because the file system there is case-sensitive. I've submitted a PR with a fix to Splash: https://github.com/JohnSundell/Splash/pull/116

**Comment by Deco354** [comment]
I'll close this for now @hybridcattt 's solution looks like what I'm after. It might make a good addition to the readme.
